### ISSUE TITLE
0.2.5 introduces a breaking change (`const fn using_offset` to `fn using_offset`)

### ISSUE THREAD

**Issue by SergioBenitez** [time-rs/time#207]
Commit https://github.com/time-rs/time/commit/8caedc3890122a3d956e4f63ea5a3781ebcde041 introduces a breaking change without bumping the major version number:

```diff
-    pub const fn using_offset(self, offset: UtcOffset) -> OffsetDateTime {
+    pub fn using_offset(self, offset: UtcOffset) -> OffsetDateTime {
```

This resulted in breakage in `cookie`: https://github.com/SergioBenitez/cookie-rs/issues/136. To resolve this issue, `time` `0.2.5` must be yanked. If this change is desired, the major version must be bumped.

**Comment by SergioBenitez** [comment]
Looking closer at https://github.com/time-rs/time/commit/8caedc3890122a3d956e4f63ea5a3781ebcde041, it seems to introduce quite a few breaking changes, many of them silent. This can cause all sorts of trouble. Please yank `0.2.5` and release `0.3.0`, ideally with a CHANGELOG that specify exactly the changes so that dependencies can migrate safely.

**Comment by jhpratt** [comment]
Crap, you're right with regard to `const fn`. I should go through and try to determine what may change in the future.

The previous behavior was not consistent, which is why the change was necessary — some uses inside `OffsetDateTime` assumed the datetime was local, others assumed it was UTC. I considered those changes to be bugfixes, as it was not clear what even _should_ have been happening if the offset wasn't UTC.

Semi-related, do you know if there are any tools like crater for individual crates? I could certainly run something locally before publishing to see if I break something else, if there is. Obviously it wouldn't be quite as large as crater, but something along those lines.

**Comment by jhpratt** [comment]
Hopefully later today, I'll try to see if there's a way to hack around compiler limits to keep it a `const fn`. I believe the other changes were necessary as bugfixes, though. I tried to preserve all pre-existing tests, but that turned out impossible (due to inconsistent behavior).

**Comment by jhpratt** [comment]
^^ It's not possible to keep things `const fn` with the behavior change.

After a discussion on IRC, I will work on a patch doing what I should have done originally — I will fix the relevant trait implementations such that comparisons are properly performed, and the old behavior will be restored (but with bugfixes).

The behavior in 0.2.5 will be released in the future as 0.3.

**Comment by SergioBenitez** [comment]
Please yank `0.2.5` in the meantime.

**Comment by jhpratt** [comment]
v0.2.6 has been published, which fixes bugs while restoring the previous (correct per documentation) functionality and function signatures.

v0.2.5 has been yanked over compatibility concerns.

Additionally, I explicitly checked to ensure cookie would compile with v0.2.6 :slightly_smiling_face:
