### ISSUE TITLE
ctime

### ISSUE THREAD

**Issue by nuxeh** [time-rs/time#216]
Hi, since the `ctime()` function has been removed, and seemingly replaced by the `%c` formatter, these two are inconsistent.

The old `ctime` function corresponds to:
`%a %b %-d %H:%M:%S %-Y`

While the new `%c` corresponds to:
`%a %b %-d %-H:%M:%S %-Y`

I just wondered if this is intentional, or not, as it made things depending on this format break for me on upgrading the `time` dependency.

Thanks!

**Comment by jhpratt** [comment]
Yes, this is intentional. Specifiers are explicitly not backwards-compatible, and I even created a tool to assist in upgrades (see #201).

I may be re-adding fixed formats, like ctime and a few RFC formats, as it would eliminate the runtime parsing of the formatting string. In theory, that will make it more performant.

But yeah, this is to be expected. Use the tool where possible. You can then think about edge cases with regard to padding, as most people don't really care what happens when the year is past 10,000, for example.
