### ISSUE TITLE
Unable to parse Year 0 using %Y

### ISSUE THREAD

**Issue by kevinpoitra** [time-rs/time#221]
I ran into this while updating a MySQL library to `time` 0.2, wherein it has to be able to handle non-strict-mode MySQL `YEAR`s of `0000`. 

```Rust
println!("Year -1: {:?}", PrimitiveDateTime::parse("-0001-02-03 11:22:33", "%Y-%m-%d %H:%M:%S"));
println!("Year 0: {:?}", PrimitiveDateTime::parse("0000-02-03 11:22:33", "%Y-%m-%d %H:%M:%S"));
println!("Year 1: {:?}", PrimitiveDateTime::parse("0001-02-03 11:22:33", "%Y-%m-%d %H:%M:%S"));
```
```
Year -1: Ok(PrimitiveDateTime { date: Date { year: -1, ordinal: 34 }, time: Time { hour: 11, minute: 22, second: 33, nanosecond: 0 } })
Year 0: Err(InvalidYear)
Year 1: Ok(PrimitiveDateTime { date: Date { year: 1, ordinal: 34 }, time: Time { hour: 11, minute: 22, second: 33, nanosecond: 0 } })
```

This isn't a problem when using `%C` or `%y` with a year of `00`, like so:
```Rust
println!("{:?}", PrimitiveDateTime::parse("00-02-03 11:22:33", "%C-%m-%d %H:%M:%S"));
println!("{:?}", PrimitiveDateTime::parse("00-02-03 11:22:33", "%y-%m-%d %H:%M:%S"));
```
```Rust
Ok(PrimitiveDateTime { date: Date { year: 0, ordinal: 34 }, time: Time { hour: 11, minute: 22, second: 33, nanosecond: 0 } })
Ok(PrimitiveDateTime { date: Date { year: 0, ordinal: 34 }, time: Time { hour: 11, minute: 22, second: 33, nanosecond: 0 } })
```

**Comment by jhpratt** [comment]
Fairly certain I know why this is happening. I'll have to think a bit on how to fix this, since it likely involves some lookahead when parsing.

**Comment by jhpratt** [comment]
Ok, on my laptop now so I can type out what is happening.

The general idea for parsing is to consume padding _then_ consume the value. For any fixed-width value types, this isn't an issue — the width of the padding is subtracted out. However, for `%Y`, it _is not_ fixed width, as years up to ±100,000 are supported. Because of this, up to 4 characters (spaces or zeroes) were stripped from the front, followed by the parsing of the value itself.

While I (presumably) initially thought 4 characters of padding was possible, it actually isn't. Even for year 0, there's only three characters followed by the actual year. As such, adjusting the 4 to 3 solves the issue entirely.

There's still a bit of an edge case where there could be 3 characters of padding followed by up to 6 characters of the value, but that leads to something being accepted, not rejected. That'll be handled as part of my eventual plan to rework the way things are consumed and how errors are returned, though; for the time being, it's something I don't particularly care about.

**Comment by kevinpoitra** [comment]
I had figured it was something to do with the library viewing all of the zeros as all padding, stripping them out, and then trying to parse an empty year string. Thanks for taking a look and fixing this!
