### ISSUE TITLE
time 0.2.8 fails to compile when cfg-if is pinned to 0.1.9

### ISSUE THREAD

**Issue by bryanburgers** [time-rs/time#233]
I'm getting the following error when trying to compile using time 0.2.8. time 0.2.7 works just fine.

```
error: expected an item keyword
   --> /Users/bryan/.cargo/registry/src/github.com-1ecc6299db9ec823/time-0.2.8/src/utc_offset.rs:366:13
    |
366 |             let tm = timestamp_to_tm(datetime.timestamp())?;
    |             ^^^

error: aborting due to previous error

error: could not compile `time`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

So far, this is as minimal of a reproduction as I can get. The following `Cargo.toml` with an empty lib.rs file.

```toml
[package]
name = "example"
version = "0.1.0"
edition = "2018"

[dependencies]
#time = "=0.2.7"
time = "=0.2.8"
phonenumber = "0.2"
```

**Comment by jhpratt** [comment]
Confirmed and investigating.

**Comment by bryanburgers** [comment]
phonenumber 0.2 lead to nom 0.5.
nom 0.5 lead to lexical-core = "^0.6.0".

So this is a more reduced reproduction.

```
[dependencies]
#time = "=0.2.7"
time = "=0.2.8"
#phonenumber = "0.2"
#nom = "5"
#nom = { version = "5", default-features = false, features = ["lexical"] }
lexical-core = "^0.6.0"
```

**Comment by jhpratt** [comment]
Note that if it's an issue with nom versions, this is not an issue with the time crate directly, but rather upstream.

**Comment by bryanburgers** [comment]
Reduced further, this also fails:

```
[dependencies]
#time = "=0.2.7"
time = "=0.2.8"
cfg-if = "=0.1.9"
```

And that, finally, makes a bit of sense, because the error message we're getting is within a cfg-if block.

**Comment by jhpratt** [comment]
Ok. I figured it had something to do with `cfg-if` ultimately, since the error reads as one from a proc-macro.

However, this only happens when it's pinned to 0.1.9. A 0.1.10 release came out six months ago. There only thing I can really do is set the minimum version of cfg-if to 0.1.10, That will cause compilation to fail, though with a much more informative error message. Ultimately, there is a version that is being pinned in some other crate, which is out of my control.

I'll push up a commit in a minute that sets the minimum version for cfg-if, but I won't be releasing it immediately — I'm going to see if any other direct dependencies could benefit from doing this as well.

**Comment by dawid-nowak** [comment]
+1 this, i wasn't even aware that my project was dependent on time until Travis started failing builds

**Comment by bryanburgers** [comment]
For information: https://github.com/Alexhuszagh/rust-lexical/commit/fefe81850e5678450ec0f001f562b182694caadf says

> Forced version `0.1.9` for cfg-if to support older Rustc versions.

**Comment by jhpratt** [comment]
@bryanburgers That's interesting, given that the MSRV is listed as 1.37 in the README. Time has an MSRV of 1.34 and works just fine. Probably worth filing an issue over there.
