### ISSUE TITLE
Can't build with no_std because of cfg-if dependency

### ISSUE THREAD

**Issue by archseer** [time-rs/time#243]
```
 └─  cargo c
    Updating crates.io index
       F       Fetch [================>                                      ]  31.39%                                                                                                        Downloaded time-macros v0.1.0
  Downloaded time-macros-impl v0.1.0
  Downloaded standback v0.2.2
  Downloaded proc-macro-hack v0.5.15
  Downloaded time v0.2.9
  Downloaded 5 crates (123.9 KB) in 0.91s
   Compiling syn v1.0.17
   Compiling rustversion v1.0.2
   Compiling standback v0.2.2
   Compiling proc-macro-hack v0.5.15
    Checking cfg-if v0.1.10
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `standback`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by archseer** [comment]
Using the new feature resolver doesn't work either, this time failing because of the macros crate:

```
 └─  cargo c -Zfeatures
    Checking standback v0.2.2
   Compiling time v0.2.9
    Checking time-macros v0.1.0
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `standback`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `time-macros`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by jhpratt** [comment]
What's in your `Cargo.toml`? And what are you trying to target?

I'll look into this once I get on my laptop.

**Comment by archseer** [comment]
```
time = { version = "0.2", default-features = false }
```

I'm trying to target a cortex-m so the toolchain is `thumbv7em-none-eabihf` where no `std` is available at all, including at build time apparently. So this won't work: https://github.com/time-rs/time/blob/02848913be1d836f72f270f070975397138a8d6e/time-macros-impl/src/ext.rs#L3

I'd be happy to have the macros behind a feature gate anyway, we won't be using them and the extra syn/proc_macro dependencies inflate compile time.

**Comment by jhpratt** [comment]
Looking at the error message again, it is failing on the `standback` crate, not `time-macros-impl`. This isn't surprising, since it would be compiled first. In the line you referenced, that is trivially replaceable with `core`.

Ultimately, the build scripts is where the issue lies. In `time`, it's not strictly necessary to use the build script — it's more for convenience on my end. In `standback`, using `std` in `build.rs` is necessary to be able to gate everything appropriately. This _may_ be possible to work around using a "force" feature, though this would lead to duplication in the binary (increasing size) unless LLVM is able to optimize it away.

**Comment by archseer** [comment]
Could we feature gate standback somehow? I don't think it's unreasonable to disable polyfills if I decide to compile on nightly.

**Comment by archseer** [comment]
I'd really prefer not to have to handroll a time library just so I can use it on embedded :/

**Comment by jhpratt** [comment]
Unfortunately disabling standback conditionally would require placing it behind a Cargo feature flag, which is a breaking change. Cargo doesn't support non-nightly dependencies or anything of that sort.

I looked into using the version_check crate, but that actually has the same problem as my current approach. I'll talk to Sergio to see if anything can be done here — I think aggressively gating tier 2/3 targets that don't have a build for std might work. Short of that, I've got nothing.

Sorry if this seems complicated; it's a side effect of the way build scripts are designed.

**Comment by archseer** [comment]
So I checked and [my target does seem to have a `rust-std` build](https://rust-lang.github.io/rustup-components-history/thumbv7em-none-eabihf.html), I could tell it was downloading it when I did `rustup update`.

A similar issue that links back to here https://github.com/deltachat/deltachat-core-rust/issues/1394 seems to indicate that I might have been running a nightly version where `rust-std` was unavailable. I'll double check in the morning.

That does make a bit more sense though, I'd expect the compiler to use std during the build step even if the actual library uses `no_std`.

**Comment by archseer** [comment]
I was able to get everything working after removing standback and putting macros under a feature flag: https://github.com/archseer/time/commit/7594c2315834209ccb62e7770c91b4818ea640f0

**Comment by jhpratt** [comment]
If that works for you, that's great. Unfortunately those changes are not feasible for the crate as a whole. Removing standback requires bumping the MSRV — that's why I created standback in the first place. Placing the macros behind a feature flag is a breaking change. Given that macros should be used in most situations (avoidance of unnecessary `unwrap`s), I'm not even sure doing that would be the correct decision. 

Don't get me wrong, I'd like to make this work on targets without a build for the standard library. I just don't think it's currently possible given the constraints across the ecosystem.

**Comment by berkowski** [comment]
Just ran into this issue myself for an embedded thumbv6m target.  I had assumed that since the crate listed `#![no_std]` support quite prominently then it would work for my use.  If it is not feasible to use this crate on targets without stdlib can we at least get a big warning in the docs to this point?

**Comment by archseer** [comment]
> Don't get me wrong, I'd like to make this work on targets without a build for the standard library.

That's just the thing, I now confirmed that my target does have a standard library, we just build with `#![no_std]` which disables it. I think the build is likely broken for all `no_std` targets, but I can't explain why it passes on the CI.

> Unfortunately those changes are not feasible for the crate as a whole.

No worries, that's understandable! I provided the commit above as a reference so the changes could potentially be made on the next major version bump. I'll probably be maintaining my fork for the time being since the diff is so minimal.

> Given that macros should be used in most situations (avoidance of unnecessary unwraps), I'm not even sure doing that would be the correct decision.

I can see that being the case in some places but we're only needing the library to parse dates (from ASN.1) and then compare those. Disabling macros is a reasonable tradeoff for us especially since syn/proc_macro_hack inflate compile times quite significantly.

**Comment by jhpratt** [comment]
@berkowski I can definitely add a disclaimer about `#![no_std]` support if I can't get things to work in the long run.

@archseer That's certainly a valid situation that wouldn't need the macros in any fashion. I can weigh the pros and cons of more aggressive feature-gating for a 0.3 release. The one disadvantage that immediately comes to mind is that the most examples use macros.

The proc macro dependencies are one-off, given Rust's incremental build capabilities, and have no runtime overhead. At least on my machine, it doesn't take terribly long, but I suppose it's all relative to the project you're working on.

And FYI, the reason it passes on CI is because none of those targets are tested. The extent of what is tested is Windows, Linux, and MacOS on 1.34 (MSRV), 1.36 (MSRV with `#![no_std]` support), and the current stable.

**Comment by berkowski** [comment]
@jhpratt Thanks, a big disclaimer would be useful.  Out of curiosity, what's the goal of supporting `#![no_std]` on non-embedded systems?

**Comment by jhpratt** [comment]
It's little extra effort and allows usage in other `#[no_std]` crates, which has more use cases than I would imagine.

**Comment by PTaylor-FluenTech** [comment]
I am currently working with the author of standback and have a PR to enable no_std usage of that crate. I will also be submitting a PR to this repo shortly as it needed a couple modifications to truly support no_std as well. I do have it working properly locally. That being said, I am relatively new to rust, so any guidance would be appreciated.

**Comment by PTaylor-FluenTech** [comment]
> @jhpratt Thanks, a big disclaimer would be useful. Out of curiosity, what's the goal of supporting `#![no_std]` on non-embedded systems?

I came to time-rs/time because the core::time::Duration struct uses unsigned values. I believe they made that decision to be more compatible with how OSs store their time values, but it's not optimal (IMO) in embedded. I want to be able to get the difference of two (custom) `Instances`s then apply that `Duration` (whether negative or positive) to another `Instance`. This is the logical way to handle times (again IMO).

**Comment by jhpratt** [comment]
Thanks for @PTaylor-FluenTech, this should be fully functional on master. I'll have a release out later tonight or tomorrow.

**Comment by archseer** [comment]
@PTaylor-FluenTech thank you so much for getting this resolved!
