### ISSUE TITLE
docs: time::PrimitiveDateTime::now is deprecated but how users should replace it?

### ISSUE THREAD

**Issue by DoumanAsh** [time-rs/time#251]
Subj, probably deprecation warning should mention what users are supposed to do

**Comment by jhpratt** [comment]
Well, what time zone are you expecting the datetime to be in? It's not clear what the `PrimitiveDateTime` method should return.

Generally speaking, you can use `OffsetDateTime::now()` to get it in UTC, and `OffsetDateTime::now_local()` to get it in your systems time zone. You can convert freely to the desired time zone from either.

**Comment by DoumanAsh** [comment]
Sure, but it is more of a question what are you planning to do with PrimitiveDateTime.

Since you're deprecating I can assume that these methods are to be removed eventually?

**Comment by jhpratt** [comment]
`PrimitiveDateTime` itself will stay around. The methods that are deprecated are because they assume an offset of UTC, which is not clear from the method name or arguments.

`OffsetDateTime` is almost certainly what people need; `PrimitiveDateTime` is only for situations where it's not sensible to have an offset. The "direct replacement" depends on what you're trying to do! That's why it's deprecated in the first place.

**Comment by DoumanAsh** [comment]
I actually think assuming UTF offset as no offset was pretty sensible, but it is up to you I guess
