### ISSUE TITLE
question: parsing full month name(%B) by abbreviated month name(%b)

### ISSUE THREAD

**Issue by zhiburt** [time-rs/time#270]
Such call `Date::parse("July 31, 2020", "%b %-d, %Y")` produces the following error`Err(UnexpectedCharacter { expected: ' ', actual: 'y' })`. I see why it's expected to get ` ` but actually gets `y`, but I spend a couple of minutes to figure this out (But I am a bad programmer :disappointed:). 

May it's better to produce something like `Err(InvalidMonth)` here?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2bc1fb7334747007fe3c2e8990c1041e

It may not be as useful but I decided to put it here.

Thank you for a great library/crate.

**Comment by jhpratt** [comment]
So the issue you're seeing is because "Jul" is the short form for July, so the parser is expecting a space to follow it (due to the formatting string provided). I'm honestly not sure how this could be worked around. Ultimately, the error _is_ correct.

At some point in the future, I do want to have better error reporting, even if that just amounts to providing an index in the string to point to. This will likely be part of 0.3, which is in progress — albeit it's been on pause for a little while as I'm quite busy.
