### ISSUE TITLE
build script does not declare dependency on COMPILING_UNDER_CARGO_WEB

### ISSUE THREAD

**Issue by Nemo157** [time-rs/time#275]
```console
> COMPILING_UNDER_CARGO_WEB=1 cargo build --target wasm32-unknown-unknown
[...]
error[E0433]: failed to resolve: use of undeclared type or module `wasm_bindgen`
[...]

> cargo build --target wasm32-unknown-unknown
[...]
error[E0433]: failed to resolve: use of undeclared type or module `wasm_bindgen`
[...]

> cargo clean

> cargo build --target wasm32-unknown-unknown
[...]
    Finished dev [unoptimized + debuginfo] target(s) in 41.81s
```

Build scripts must use [`cargo:rerun-if-env-changed`](https://doc.rust-lang.org/nightly/cargo/reference/build-scripts.html#rerun-if-env-changed) to declare the environment variables they depend on, otherwise Cargo will use the previously cached run.

From discussion on the community discord https://discord.com/channels/273534239310479360/274215136414400513/753183573145681940

**Comment by jhpratt** [comment]
Ah, my bad. I was under the interpretation that the build script was always run _unless_ there was a "rerun-if" emitted, in which case it would trigger only when necessary.

What's the proper thing to do here? Would pushing a release with an updated build script suffice, or does the change have to be reverted? I'd like to avoid reverting if possible, since the intent behind the switch to begin with was to avoid `cfg` conflicts with other crates.

**Comment by Nemo157** [comment]
The default is to only rerun if any file changes, it doesn't track environment variables at all. A new release that prints the `rerun-if` line should work.

**Comment by jhpratt** [comment]
Ok, thanks. I'll get a release out later today or tomorrow, as I uncovered a couple other bugs while expanding test coverage.
