### ISSUE TITLE
`tzset` is MT-safe env, possibly unsound

### ISSUE THREAD

**Issue by theguywithabuy** [time-rs/time#324]
I was looking at the time crate wondering why the [time crate didn't give offsets](https://github.com/time-rs/time/issues/293), and I stumbled upon [this thread on Internals](https://internals.rust-lang.org/t/function-to-hold-lock-on-execution-environment-for-ffi/13702/22). This seems like a big problem so I went looking for FFI crates where this could be a problem.

It looks like I'm right back to where I started, as I found a use of `tzset` https://github.com/time-rs/time/blob/172eacea0fe67d2e0ec6f2b6b784a42e70979061/src/utc_offset.rs#L374, which while MT-safe, is MT-safe env, which means this crate can race with `set_env` on another thread.

**Comment by jhpratt** [comment]
This is correct, which is why it's gated behind a user-provided `unsound_local_offset` cfg. If a user provides that cfg when compiling, it's on them (it has "unsound" in the name for a reason). This code was initially commented out, but has been re-exposed behind the aforementioned flag for 0.3.

Note that this change was made _in response to_ #293 as you may have noticed. The internals thread was created by me in an attempt to resolve this unsoundness.

**Comment by xerxes12354** [comment]
Thanks for the changes, it will be useful so I do not have to use libc and do it myself.

**Comment by jhpratt** [comment]
Keep in mind that the usage _is still unsound_ if you enable that cfg. It's just on you to verify the validity. Libraries cannot (easily, at least) enable the flag.

**Comment by ririsoft** [comment]
@jhpratt : would you consider adding `unsound_local_offset` as an optional opt-in feature to ease usage through cargo.toml instead of requiring users to use cfg flags at compile time, please ?

**Comment by jhpratt** [comment]
The behavior is intentional such that libraries cannot enable it _and_ that it must be passed as a flag every time the end binary is compiled. It serves as a persistent as a reminder that it is **unsound** to do this and does not require `unsafe`. While I understand this is undesirable, that's the point.

**Comment by ririsoft** [comment]
Thank you for the prompt answer, it is clear: I totally missed the point that some libraries could enable it without end users knowing the potential danger here. I went through lots of reading from rust to glibc and I loved it, very interesting corner case. Thank you for all those discussions.

My understanding it that we are still in a danger zone here. The case I have in mind is the following (this is totally theoretical and unlikely but still ...)

- One library developer uses `UtcOffset::current_local_offset` in a multi-thread context without building with cfg `unsound_local_offset ` for its tests. So far so good.

- Another developer uses above library as a dependency and builds with `unsound_local_offset ` because he knows that its usage of `UtcOffset::current_local_offset` is safe. We could see some segfault, and the developer might have hard time understanding the issue since his usage is supposed to be safe.

I would personally prefer that the unsound methods are marked `unsafe` so that library developers are discouraged to use those directly and instead build APIs requesting an `UtcOffset` as parameter when needed, leaving the responsibility to top level crates to use the `unsafe` methods or not to get local utc offset.

I may be wrong but opening some features (unsound or not) with cfg compilation flags is something we rarely see in crates. We rather have features or unsafe functions.

On the other side it is unfair to some platforms that handle this case correctly (Windows and maybe some BSDs ?). I admit I I do not know if we can have this unsafe for some platforms and safe for some others ?

What do you think ? Are you opposed to mark those functions as `unsafe` ?

**Comment by jhpratt** [comment]
> My understanding it that we are still in a danger zone here. The case I have in mind is the following (this is totally theoretical and unlikely but still ...)
> 
>   * One library developer uses `UtcOffset::current_local_offset` in a multi-thread context without building with cfg `unsound_local_offset ` for its tests. So far so good.
> 
>   * Another developer uses above library as a dependency and builds with `unsound_local_offset ` because he knows that its usage of `UtcOffset::current_local_offset` is safe. We could see some segfault, and the developer might have hard time understanding the issue since his usage is supposed to be safe.

Yes, this is possible. It is wholly on the user compiling the end binary to ensure that _all_ usage is sound, including usage not in their crate. This is unquestionably dangerous and can cause segfaults, hence the security vulnerability. The only reason I am even reintroducing behavior behind a user-provided flag is because the functionality is so widely desired.

> I would personally prefer that the unsound methods are marked `unsafe` so that library developers are discouraged to use those directly and instead build APIs requesting an `UtcOffset` as parameter when needed, leaving the responsibility to top level crates to use the `unsafe` methods or not to get local utc offset.

Frankly, I don't believe libraries will be responsible enough to avoid this. I have seen a number of libraries pin time to the last version before this functionality was removed despite the unsoundness of it. I've no doubt that libraries will disregard the fact that they quite literally cannot validate safety in any circumstance.

> I may be wrong but opening some features (unsound or not) with cfg compilation flags is something we rarely see in crates. We rather have features or unsafe functions.

This is admittedly uncommon. I got the idea from the `proc-macro2` crate, which does the same for nightly-only features [[ref]](https://docs.rs/proc-macro2/1.0.27/proc_macro2/#unstable-features).

> On the other side it is unfair to some platforms that handle this case correctly (Windows and maybe some BSDs ?). I admit I I do not know if we can have this unsafe for some platforms and safe for some others ?

Theoretically? Sure, it's possible to be `unsafe` only on *nix platforms, but that would be an _enormous_ inconsistency that would require every user everywhere to be aware and have platform-specific behavior.

> What do you think ? Are you opposed to mark those functions as `unsafe` ?

I am for the reasons stated above. I don't believe libraries will do the appropriate thing nor do I think that platform-specific behavior is the right thing to do.

**Comment by ririsoft** [comment]
Thank you again @jhpratt for taking the time to explain your position. It is very clear and there is no much left to say.
All in all using `unsafe` or cfg flags are both unsatisfying solutions. We will have to wait for a glibc fix (it might even never come) or a pure `GetLocalUTCOffset` rust implementation, thread safe.
