### ISSUE TITLE
MacOS version 11.3.1 try_now_local always returns Err(IndeterminateOffset)

### ISSUE THREAD

**Issue by Firstyear** [time-rs/time#325]
```
fn main() {
    let now = time::OffsetDateTime::try_now_local();
    println!("Hello, world! {:?}", now);
}

[dependencies]
time = "0.2"
```

With this reproducer, everytime this is called, `Err(IndeterminateOffset)` is produced. 

I have not been able to investigate further as to why this may be :(

**Comment by jhpratt** [comment]
See #293. This behavior is intentional.

**Comment by Firstyear** [comment]
@jhpratt this is on time 0.2.26 which is apparently patched according to https://github.com/time-rs/time/security/advisories/GHSA-wcg3-cvx6-7396

**Comment by jhpratt** [comment]
Correct. The issue was regarding soundness — certain situations could cause a segfault originating in the time crate. Versions >= 0.2.26 do not have that issue. The side effect being that it's necessary to return the error variant, as any attempt at attaining the local UTC offset could result in a segfault on *nix platforms.

**Comment by Firstyear** [comment]
So what you're saying is today, that there is no way on MacOS or Linux to determine the UTC offset with the `time` crate. Is that correct?

**Comment by jhpratt** [comment]
That is correct by default, as doing so would be unsound. The soundness issue exists in chrono as well, as they have not gotten around to fixing it.

Note that for time 0.3 (there's currently an alpha release out), it _is_ possible to pass `RUSTFLAGS="--cfg unsound_local_offset" when building the final binary. Doing so is still unsound, however.
