### ISSUE TITLE
Month conversion to/from integral numbers

### ISSUE THREAD

**Issue by dmit** [time-rs/time#345]
**Preamble**

As of version 0.3.0, the `Month` enum is a complete black box. It has no safe way of converting to/from numbers, and it even intentionally doesn't implement `Ord` or `PartialOrd`.

In my experience, there are valid use cases where you want those features. Here's one example:

```rust
pub fn age_at(date: Date, birthday: Date) -> Year {
    let (year, month, day) = date.to_calendar_date();
    let (year_b, month_b, day_b) = birthday.to_calendar_date();

    if (month_b.ordinal(), day_b) <= (month.ordinal(), day) {
        year - year_b
    } else {
        year - year_b - 1
    }
}
```

Another use case is date arithmetic. I realize that "date + 10 months" is a giant can of worms, but sometimes you have no choice but to crack that can open.

**Proposal**

How about `impl From<Month> for u8` and `impl TryFrom<u8> for Month`? I feel like these are fairly reasonable things to add to the library. The error type for the latter would be `time::error::ComponentRange`.

**Comment by jhpratt** [comment]
Going _to_ a number can already be done — `month as u8`. Months have their value explicitly assigned, so you'll get the value you expect. For getting the month from the number, I could certainly expose that. The reason I didn't initially is likely because I needed it to be `const`, and const trait impls aren't a thing yet. There is a `Month::from_number(NonZeroU8) -> Result<Month, error::ComponentRange>` that exists internally, though.

If you're looking to get "date + 10 months", that's planned as a `Period` type in the future. I intend on having it in the 0.3 series.

**Comment by dmit** [comment]
> Going _to_ a number can already be done — `month as u8`.

That's why I wrote "no _safe_ way" to get there. `as` is a ticking footgun, and while `#[repr(u8)]` shows up in the docs, it's unclear if it's 1-based unless you look at the source.

Glad to hear that `Period` is still on track to be added!

**Comment by jhpratt** [comment]
I should probably document that it's 1-based now that you mention it.

And I don't know about "on track" — I haven't done any implementation work at all. It's _planned_, though.
