### ISSUE TITLE
Unexpected `Neg` behavior on `Duration`

### ISSUE THREAD

**Issue by ghost** [time-rs/time#367]
This code panics in debug builds and have unexpected result in release build.
```rust
use time::Duration;

fn main() {
    let duration = Duration::MIN;
    println!("{:?}", duration);
    println!("{:?}", -duration);
}
```
This is because of how signed integers work. `i64::MIN` has no positive counterpart i.e. `i64::MIN == -i64::MIN`.
Meanwhile I'll add `const fn checked_neg(self)` method to `Duration` impls, it is required for other checked arithmetic, mentioned in #364 .

**Comment by L117** [comment]
Actually, there's a lot of places in code where subtraction is defined via negation and add. So, this also panics in debug builds:
```rust
use time::Duration;

fn main() {
    assert_eq!(Duration::MIN - Duration::MIN, Duration::ZERO);
}
```

**Comment by jhpratt** [comment]
The panic is deliberate due to the overflow. The only real issue uncovered here is that relying on negation for implementing subtraction isn't ideal. I'll fix that be implementing it directly where appropriate, but it's not going to be a high priority for me given the unlikeliness of running into it in the wild.
