### ISSUE TITLE
Convert OffsetDateTime back to PrimitiveDateTime

### ISSUE THREAD

**Issue by DenisKolodin** [time-rs/time#390]
I know there are some discussions about converting `OffsetDateTime` to `PrimitiveDateTime`, but there is no a way to do that simply.

Since `chrono` used old version of `time` some projects considered to switch directly to the latest `time` crate, but there is a problem: `chrono` provides `naive_local` and `naive_utc` [methods](https://docs.rs/chrono/0.4.19/chrono/struct.DateTime.html#method.naive_utc), and it's not easy to use `time` directly if the project uses `NaiveDateTime` and already stored some data using that format (without timezone).

Is there any reason we don't have `From<OffsetDateTime> for PrimitiveDateTime` implementation? It could help to move from the `chrono` crate easier.

**Comment by jhpratt** [comment]
> if the project uses `NaiveDateTime` and already stored some data using that format (without timezone).

That's the problem. You're trying to use `PrimitiveDateTime` for something where you should be using `OffsetDateTime`. `impl From<OffsetDateTime> for PrimitiveDateTime` won't be added in any situation because there is no `UtcOffset` that is always correct.

This was recently requested in #369. There is no reason that I see that you can't use `.date()` and `.time()`, recombining them into a `PrimitiveDateTime` if that's what you truly want. In #369 benchmarks were raised, but those were flawed. These methods aren't guaranteed to be free, regardless.

**Comment by DenisKolodin** [comment]
@jhpratt Thanks 🙂
