### ISSUE TITLE
`serde-human-readable` feature can cause surprising breakage

### ISSUE THREAD

**Issue by lilyball** [time-rs/time#414]
I'm writing code to make use of `time::Date`'s handling of the `serde-human-readable` feature flag right now, and it occurs to me that this flag is actually rather dangerous and violates the intended use of feature flags.

In particular, serde is typically assumed to serialize with a stable format, allowing you to persist the serialized data to disk and read it back in later from a different process instance. This doesn't strictly require the serialization format to be stable, but it does require it to always be able to deserialize any previously-serialized form.

The danger here is the `serde-human-readable` flag changes the serialization format (for human-readable formats) just by being turned on. This certainly is convenient! But it means that I can add or update a dependency that sets this feature, and now serialization of `time::Date` has changed across my whole app.

We could try saying something like "this feature should only ever be enabled by apps, not libraries" as an attempt at reducing the impact (assuming anyone listens), but that means libraries can't take advantage of serde if they need the human-readable serialization form.

At a bare minimum, I think this requires that all types that respect this feature should fall back to trying to deserialize the non–human-readable format if reading the human-readable one fails (though be careful of the errors, they should presumably return the error from the human-readable deserialize failure instead of from the fallback). That way if the flag does get turned on by a dependency addition/update, existing serialized values will continue to be deserialized, though it means that any subsequently-serialized values will be different and this can be a problem.

Arguably, if the flag is _off_, it should fallback to attempting to deserialize the human-readable version too, in case a dependency update/removal disables the flag when it was previously enabled.

I'm inclined to say that both of these mitigations should be done; the flag should belong to the app alone to keep the format more stable, and the `Deserialize` impls should fall back to attempting the alternative behavior.

And to add to that, the human-readable formats that the types currently implement should be exposed publicly, so that way I can write my own encode/decode routines easily that match it. This way I can e.g. read in a value serialized by a different app without turning the flag on.

**Comment by jhpratt** [comment]
What you call the "bare minimum" is absolutely that. To the extent that I _thought_ that's what I actually implemented initially. As such it's definitely a bug and will be fixed on main soon. I'm planning a release within the next week or so.

Libraries _probably_ shouldn't use this feature, but I might be missing a use case. I'll add a note in documentation to this effect. The only way to strictly enforce that binaries and not libraries use this feature is quite the hack and only used in extenuating circumstances (currently the `unsound_local_offset` does this).

> And to add to that, the human-readable formats that the types currently implement should be exposed publicly, so that way I can write my own encode/decode routines easily that match it. This way I can e.g. read in a value serialized by a different app without turning the flag on.

This might happen in the future, but not right now.

> Arguably, if the flag is off, it should fallback to attempting to deserialize the human-readable version too, in case a dependency update/removal disables the flag when it was previously enabled.

This is tricky due to the way human-readable parsing is handled. I _might_ be able to do this, but it would have a fair amount of overhead.

---

In a future breaking release, I am considering requiring the use of a serde attribute to handle the human-readable case, which would alleviate every single concern here.

**Comment by jhpratt** [comment]
All types now use custom visitors, which has the benefit that they fall back automatically. I'm going to investigate the extent to which I can loosen the feature flags such that human-readable formats can be parsed even without `serde-human-readable` enabled. Once that is done and a note in documentation is made, I'll close this issue.
