### ISSUE TITLE
API mismatch between `Parsed::with_offset_*` and `UtcOffset:{minutes_after_hour,seconds_after_minute}`

### ISSUE THREAD

**Issue by vincentdephily** [time-rs/time#436]
Context: I'm parsing dates from the CLI, which are assumed to be local time unless a `--utc` flag has also been set. So I grab a `UtcOffset` at program start and initialize my `Parsed` with it.

Because of the `i8` (UtcOffset) vs `u8` (Parsed), the initialization looks like this:
```rust
let mut p = Parsed::new()
                 .with_offset_hour(offset.whole_hours())
                 .unwrap()
                 .with_offset_minute(offset.minutes_past_hour().try_into().unwrap())
                 .unwrap()
                 .with_offset_second(offset.seconds_past_minute().try_into().unwrap())
                 .unwrap();
```
This is inconvenient and error-prone (I nearly used `offset.whole_minutes().try_into().unwrap()`).

Also, it seems to me that the Parsed API is incapable of handling a sub-hour negative offset ? There's no such timezone in the real world, but it still feels dissatisfying.

I propose these new `Parsed` methods to fix this: `with_offset(self, UtcOffset) -> Self`, `with_time(self, Time) -> Self`, `with_date(self, Date) -> Self`, and the `set_` equivalents. The date and time versions are here for consistency, but it's not hard to imagine usecases that would benefit from them. AFAICT these methods should be infallible, an added usability gain.

**Comment by jhpratt** [comment]
> Also, it seems to me that the Parsed API is incapable of handling a sub-hour negative offset? 

I just checked — this is unfortunately correct. I will introduce a field and relevant methods to set the sign explicitly. The format description would still require the offset hour to be present to set the sign, but it should realistically be present in any situation.

Adding methods to set the offset, date, and time seem reasonable due to the obvious benefit. They _will_ be fallible, though, as future checks for consistency might be implemented (in this situation tzdb would be required for checks). This is similar to how `set_month` and `set_weekday` are fallible. Right now nothing, not even range validity, is actually checked on setting, but I want to keep that possibility open.

**Comment by vincentdephily** [comment]
Case in point: the code above is buggy, correct one is `.with_offset_minute(offset.minutes_past_hour().abs().try_into().unwrap())` or `.with_offset_minute(offset.minutes_past_hour().abs() as u8)` :sweat_smile:

**Comment by vincentdephily** [comment]
I'll make a PR for the new `set/with` methods in the next few days - that sounds like a good first-time-issue.

**Comment by jhpratt** [comment]
Coming back around to this, I'm going to fix the buggy behavior shortly. I've changed my mind on `with_date` and similar methods. Ultimately the `Parsed` struct is intended for parsing, and there's no component for a full date, time, or offset.

**Comment by jhpratt** [comment]
I've just pushed a commit that fixes this to the extent possible. The existing methods (getters, setters, and builders) have been deprecated and replaced with signed equivalents. The now-deprecated methods will attempt to convert to the signed value and fail if not possible.
