### ISSUE TITLE
no millis?

### ISSUE THREAD

**Issue by hp8wvvvgnj6asjm7** [time-rs/time#539]
Am I missing something here?
```
println!("{:?}", OffsetDateTime::now_utc().unix_timestamp_nanos());
...? micros
...? millis
println!("{:?}", OffsetDateTime::now_utc().unix_timestamp());
```

**Comment by jhpratt** [comment]
Multiply it by 1000 or 1,000,000 and use `unix_timestamp_nanos`. The only reason there are even two methods is because they accept different types.

**Comment by jhpratt** [comment]
I'm not sure I follow. A `Duration` and an `OffsetDateTime` are two completely different types with zero overlap in functionality.

**Comment by AshfordN** [comment]
On this note, I think it is important to explicitly state, in the docs, that the `*_unix_timestamp()` functions operate on seconds, as opposed to some other unit, such as milliseconds. I know it should be understood or expected that all Unix timestamps are in second, but this omission could potentially lead to confusion and ambiguity, since some external APIs, such as Javascript's Date API (in the context of a WASM module), returns millisecond timestamps.

**Comment by jhpratt** [comment]
@AshfordN The Unix timestamp is, by definition, in seconds.
