### ISSUE TITLE
Relation between `time::error::Error` and `time::error::Parse`?

### ISSUE THREAD

**Issue by nc7s** [time-rs/time#558]
I tried to use `time::error::Error` as the source in my own error type, but rustc complains that result of `Date::parse()` is `time::error::Parse`. Is this distinction by design? Also, `Error`'s doc says it's "A unified error type for anything returned by a method in the time crate". What's `Parse`'s place here?

**Comment by jhpratt** [comment]
`time::error::Parse` is what is returned (and what should be used) when you are _only_ parsing. `time::error::Error` can store _any_ error type from `time`, such as if a component is out of range, obtaining the local offset failed, etc. Naturally, it can also store every variant of `time::error::Parse`.

In the future, please open a discussion rather than an issue for questions like this. It helps avoid clutter in the issue tracker.

**Comment by bnoctis** [comment]
Ah, I'm not used to using discussions yet, sorry.
