### ISSUE TITLE
Can i try to implement `Time::parse` equivalents?

### ISSUE THREAD

**Issue by JonasFocke01** [time-rs/time#636]
Hi,

im using this crate quite a while now, and i noticed, that there is a `Time::parse(&str, format)`, but no `Date::parse, DateTime::parse` or `Duration::parse`.  
Is there the something already going, that implements this?  
Or can i try to do this?

**Comment by jhpratt** [comment]
There are `parse` methods on `Time`, `Date`, `UtcOffset`, `PrimitiveDateTime`, and `OffsetDatetime`, so I'm not certain what you're looking at.

`Duration` is quite different than those, and is not something I am currently interested in. This is because the format that would be expected would be severely limiting to the point of losing nearly all utility.
