### ISSUE TITLE
Error with rust-nightly: type annotations needed for `Box<_>`

### ISSUE THREAD

**Issue by dessalines** [time-rs/time#681]
Error:

```
/home/xxx/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.34/src/format_description/parse/mod.rs:83:9
let items = format_items
consider giving `items` an explicit type, where the placeholders `_` are specified
let items: Box<_> = format_items
```

I'll have a PR shortly, hopefully clippy's suggestion will fix.

**Comment by JosiahParry** [comment]
@dessalines, I am running into this issue at present with both nightly and 1.78 docker images. How did you address it?

**Comment by dessalines** [comment]
For me it was as simple as running `cargo update`. Make sure you open issues if there's a crate you're using that hasn't updated.

**Comment by mladedav** [comment]
If ai understand it correctly, the code used to compile but doesn't with newer versions of the compiler? How is this not an issue in rustc? Something changed that broke backwards compatibility and that should not happen, right?

**Comment by jhpratt** [comment]
I haven't looked into this at all, but my understanding from discussions elsewhere is that this was fixed by #671. `time` was caught in a crater run when a new trait implementation was added to the standard library. While it is a breaking change, it is considered acceptable breakage because the alternative is never adding any trait implementations or methods.

**Comment by iitalics** [comment]
would it be possible to backport a fix for this?

**Comment by jhpratt** [comment]
@iitalics That's impossible.
